name = "OptLibrary"
uuid = "3cbf7d3e-808f-4706-8d10-7842e8ec0698"
authors = ["Pengfei Song"]
version = "0.1.0"

[deps]
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"

[compat]
Optimization = "3"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
